# Generated by Django 4.1.1 on 2022-10-06 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0006_auto_20220926_1138"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"ordering": ["-points", "username"], "verbose_name": "user"},
        ),
    ]
