# Generated by Django 4.1.1 on 2022-11-17 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0008_alter_user_fav_products_alter_user_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product", name="state", field=models.IntegerField(default=1),
        ),
    ]
