# Generated by Django 4.1.1 on 2022-11-17 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0009_product_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="owner",
            field=models.CharField(default="LINKY", max_length=100),
        ),
    ]
