# Generated by Django 2.2.5 on 2022-09-20 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
