# Generated by Django 4.1.1 on 2022-10-06 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0007_alter_user_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="fav_products",
            field=models.ManyToManyField(blank=True, null=True, to="app1.product"),
        ),
        migrations.AlterField(
            model_name="user",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="media/%y/%m/%d"),
        ),
        migrations.AlterField(
            model_name="user", name="num_visits", field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="user", name="points", field=models.IntegerField(default=0),
        ),
    ]
